### ISSUE TITLE
Fix exponentialBackoff test

### ISSUE THREAD

**Issue by jgleal** [guidesmiths/systemic-azure-bus#40]

**Comment by reymon359** [comment]
@rakelqr @jgleal I have been having a look at this issue and 2 things happen:
- The first is that this connection error pops up some times
![Screenshot 2021-02-16 at 16 18 16](https://user-images.githubusercontent.com/31936665/108083468-61d79380-7073-11eb-92ed-7b68c8f8ea37.png)

- The second is that the test enters an infinite loop on the `onMessageHandler`. I had a look at the code for solving it but couldn't. I left a video that may help you 😉 

 https://user-images.githubusercontent.com/31936665/108083491-69973800-7073-11eb-80a1-a4764596a0d6.mov

It would be awesome to have a look at this with you guys when you have time or at the next meeting 😊
